### ISSUE TITLE
作業_範本

### ISSUE THREAD

**Issue by roberthsu2003** [roberthsu2003/cAndC-#22]
### 請輸出剛才老師打的內容

```
#include <stdio.h>

int main(void) {
  printf("Hello C語言\n");
  printf("這是c語的第一節課\n");
  printf("這是一個線上真人課程\n");
  return 0;
}
```

**Comment by lihua1018** [comment]
```
#include <stdio.h>

int main(void) {
  printf("Hello C 語言\n");
  printf("這是c語言的第一堂課\n");
  printf("這是一個線上真人課程\n");

  return 0;
}
```
<img width="604" alt="image" src="https://github.com/roberthsu2003/cAndC-/assets/88178674/26281c98-08bd-4b06-8546-e4450cfa2884">

**Comment by fjkppol** [comment]
![image](https://github.com/roberthsu2003/cAndC-/assets/159032415/00406039-2eb5-4532-b59c-e5c593e65181)

這樣對嗎?
