### ISSUE TITLE
同學有問題！看哪位同學可以幫忙

### ISSUE THREAD

**Issue by roberthsu2003** [roberthsu2003/cAndC-#32]
老師您好 
我昨天練習求出亂數值的最大值和最小值，但結果error，不清楚哪裡錯誤
```
#include <iostream>
#include <time.h>
using namespace std;

int main() {  
  srandom(time(NULL));
  int min =1;
  int max =99;
  int nums;
    cout << "請輸入元素數量:";
    cin >> nums;
    int n[nums];
    //輸入
    for (int i = 0; i < nums; i++) {
      n[i] = random() % (max - min + 1) + min;
    }

    //輸出
  int max_value = n[0];
  int min_value = n[0];
  for (int i = 0; i < nums; i++) {
      cout << "第" << i + 1 << "個元素:";
      cout << n[i] << endl;
      if (n[i] > max_value) {
        max_value = n[i];
      }
      if (n[i] < min_value) {
        min_value = n[i];
     }
    cout << "最大值為:" << max_value << endl;
    cout << "最小值為:" << min_value << endl;
   
}
```

**Comment by roberthsu2003** [comment]
> 老師您好 我昨天練習求出亂數值的最大值和最小值，但結果error，不清楚哪裡錯誤
> 
> ```
> #include <iostream>
> #include <time.h>
> using namespace std;
> 
> int main() {  
>   srandom(time(NULL));
>   int min =1;
>   int max =99;
>   int nums;
>     cout << "請輸入元素數量:";
>     cin >> nums;
>     int n[nums];
>     //輸入
>     for (int i = 0; i < nums; i++) {
>       n[i] = random() % (max - min + 1) + min;
>     }
> 
>     //輸出
>   int max_value = n[0];
>   int min_value = n[0];
>   for (int i = 0; i < nums; i++) {
>       cout << "第" << i + 1 << "個元素:";
>       cout << n[i] << endl;
>       if (n[i] > max_value) {
>         max_value = n[i];
>       }
>       if (n[i] < min_value) {
>         min_value = n[i];
>      }
>     cout << "最大值為:" << max_value << endl;
>     cout << "最小值為:" << min_value << endl;
>    
> }
> ```

這個程式碼出現了一個小問題,copy程式至replit內執行,比較能夠發現問題,看同學可以發現bug在何處嗎?

**Comment by vinceyeh** [comment]
for 迴圈少了一個 }
```
#include <iostream>
#include <time.h>
using namespace std;

int main() {  
  srandom(time(NULL));
  int min =1;
  int max =99;
  int nums;
    cout << "請輸入元素數量:";
    cin >> nums;
    int n[nums];
    //輸入
    for (int i = 0; i < nums; i++) {
      n[i] = random() % (max - min + 1) + min;
    }

    //輸出
  int max_value = n[0];
  int min_value = n[0];
  for (int i = 0; i < nums; i++) {
      cout << "第" << i + 1 << "個元素:";
      cout << n[i] << endl;
      if (n[i] > max_value) {
        max_value = n[i];
      }
      if (n[i] < min_value) {
        min_value = n[i];
     }
}
    cout << "最大值為:" << max_value << endl;
    cout << "最小值為:" << min_value << endl;
}
```
