### ISSUE TITLE
想將上課內容變成執行檔，在replit是正確的，但到dev卻錯誤，請問如何改善?謝謝

### ISSUE THREAD

**Issue by estelaOAO** [roberthsu2003/cAndC-#36]
![問題1](https://github.com/roberthsu2003/cAndC-/assets/163852709/f4b83ffc-e083-4f29-bcdc-3b2f7353b5be)

**Comment by roberthsu2003** [comment]
Step1. 1個專案是一個資料夾
Step2. 資料夾內要1個主要執行檔，main.cpp
Step3. main.cpp內要有一個main() function!

你提供的圖片！這3個我全沒看到

**Comment by roberthsu2003** [comment]
參考YouTube
https://youtu.be/NfDys5ue6DI?si=btQ9Q8AeNER8icuW

**Comment by estelaOAO** [comment]
老師 我這是貼上上課的內容 在網站上可以正常運行 ，經過這個影片後再試還是不行

徐國堂 ***@***.***>於 2024年3月30日 週六，下午7:05寫道：

**Comment by roberthsu2003** [comment]
以下是建立c++ 專案的方式(0:0到1:30秒)
是建立c++專案

https://youtu.be/8nVIp9EOiR4?si=KQS5X7zF_GORHpMp

**Comment by estelaOAO** [comment]
我的步驟跟他一樣，但不行


徐國堂 ***@***.***> 於 2024年3月31日 週日 下午5:06寫道：

**Comment by roberthsu2003** [comment]
由於你給的資訊太少！我不知道何處出問題

**Comment by estelaOAO** [comment]
[image: image.png][image: image.png][image: image.png]全部長這樣

徐國堂 ***@***.***> 於 2024年4月3日 週三 上午8:23寫道：

**Comment by roberthsu2003** [comment]
同學你好！
我的回覆都是在GitHub 上！麻煩你看一下你在GitHub上的回覆！

也希望你在每一個回覆！都認真一些

**Comment by estelaOAO** [comment]
謝謝您

徐國堂 ***@***.***>於 2024年4月3日 週三，下午9:18寫道：
