### ISSUE TITLE
老師您好：我有以下問題想請教您

### ISSUE THREAD

**Issue by RJTseng** [roberthsu2003/cAndC-#4]
1. 在二分搜尋法解題中有出現 for(;;) ，想請教在這邊的用意是為什麼呢？謝謝

2. 想請問在C語言中，LinkedList 的反轉問題 (在網路上搜尋過很多解法，但都看得我邏輯好亂QQ)

再麻煩老師回覆，謝謝 ：)

**Comment by roberthsu2003** [comment]
1.for(;;) ->代表無限迴圈
