### ISSUE TITLE
新手求解

### ISSUE THREAD

**Issue by pathsu0310** [roberthsu2003/cAndC-#7]
![未命名](https://user-images.githubusercontent.com/70913764/92411242-9a487c80-f179-11ea-9f24-636013de0088.png)

大家好, 剛在學寫程式而已
想嘗試用迴圈計算這個
但是"参天花費"一直都是10
請問是哪裡出了錯....

**Comment by roberthsu2003** [comment]
<img width="959" alt="issue7" src="https://user-images.githubusercontent.com/1614274/94238422-f1549c80-ff42-11ea-8458-895cc2381be0.png">
