### ISSUE TITLE
大樂透問題

### ISSUE THREAD

**Issue by TonyLiu1221** [roberthsu2003/cAndC-#8]
![擷取](https://user-images.githubusercontent.com/83959591/117658728-ad5e9100-b1cd-11eb-8c88-da9171ac9b22.PNG)
老師好，之前有向您請問大樂透題目的問題
我已經理解紅框處的意義在於把已經選到的數字與最後一個數字交換位置，然後扣掉做最後一個位置取剩下下數字，就不會導致重複。但我想問的是為何可以直接寫lot[randIndex]=lot[maxIndex]就讓此兩索引位置的數字交換，而不用使用類似像是Swap的函數交換呢?  謝謝老師

**Comment by roberthsu2003** [comment]
這是1~3次的動作，注意random的範圍
<img width="595" alt="截圖 2021-05-11 下午6 38 50" src="https://user-images.githubusercontent.com/1614274/117802608-44881f00-b288-11eb-9fb6-64e8ee9b030a.png">

**Comment by TonyLiu1221** [comment]
謝謝老師解答，圖很清楚，我已經理解了，謝謝老師
